# Generated by Django 5.0.2 on 2024-03-16 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_shift_alter_user_role_staff_timeoffrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='schedule',
        ),
        migrations.AddField(
            model_name='shift',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='account.staff'),
        ),
    ]
