# Generated by Django 5.0.2 on 2024-03-18 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_staff_schedule_shift_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoffrequest',
            name='date_from',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='timeoffrequest',
            name='date_to',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
