# Generated by Django 5.0.2 on 2024-03-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='schedule',
            field=models.DateTimeField(),
        ),
    ]
