# Generated by Django 5.0.2 on 2024-02-27 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_remove_order_created_at_remove_order_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='total_amount',
        ),
    ]
