# Generated by Django 5.0.2 on 2024-03-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_remove_staff_schedule_staff_day_staff_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='shift',
            field=models.CharField(choices=[('MORNING', 'Morning'), ('DAY', 'Day'), ('EVENING', 'Evening')], default='Day', max_length=10),
        ),
        migrations.AlterField(
            model_name='staff',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
