# Generated by Django 5.0.2 on 2024-03-15 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_staff_shift_alter_staff_end_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
